# Generated by Django 2.2.24 on 2021-10-20 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20211020_1350"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="phone",
            new_name="mobile",
        ),
    ]
