# Generated by Django 2.2.24 on 2021-10-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_gigaccount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gigaccount",
            name="phone_number",
            field=models.CharField(max_length=50),
        ),
    ]
